<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.0 setup script
 * Date: Sun, 24 Jul 2022 02:53:02 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: togetherwegrow.cfq3tnuayhgb.ca-central-1.rds.amazonaws.com [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'togetherwegrow.cfq3tnuayhgb.ca-central-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'userjc';
$cfg['Servers'][$i]['password'] = 'capstone';

/* End of servers configuration */

$cfg['blowfish_secret'] = '2YCr{,*YGO?T9Q3d@Vd`N}Fr\'{b`Lss+';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

